apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {appName}
  name: {appName}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: gp2
