apiVersion: v1
kind: Service
metadata:
  name: {appName}
  namespace: {namespace}
  labels:
    app: {appName}
spec:
  ports:
  - name: {appName}
    port: 8080
    protocol: TCP
  selector:
    app: {appName}